# Generated by Django 2.2.24 on 2022-05-01 21:07

from django.db import migrations


class Migration(migrations.Migration):
    def set_new_building(apps, schema_editor):
        Flat = apps.get_model('property', 'Flat')
        for flat in Flat.objects.all():
            flat.new_building = False
            if flat.construction_year > 2014:
                flat.new_building = True
            flat.save()

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(set_new_building)
    ]
