# Generated by Django 2.2.24 on 2022-05-01 21:07

from django.db import migrations


class Migration(migrations.Migration):
    def set_new_building(apps, schema_editor):
        Flat = apps.get_model('property', 'Flat')
        flats = Flat.objects.all()
        if flats.exists():
            for flat in flats.iterator():
                flat.new_building = flat.construction_year > 2014
                flat.save()

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(set_new_building)
    ]
