# Generated by Django 2.2.24 on 2022-05-01 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint_text',
            field=models.TextField(verbose_name='Текст жалобы'),
        ),
    ]
