# Generated by Django 2.2.24 on 2022-05-16 17:04

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20220516_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='owner_pure_phonenumber',
        ),
        migrations.AddField(
            model_name='flat',
            name='owner_pure_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='RU', verbose_name='нормализованный номер владельца'),
        ),
    ]
