# Generated by Django 2.2.24 on 2022-05-17 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_auto_20220517_2013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='flats',
            new_name='owner_flats',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owner_name',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owner_pure_phone',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owners_phonenumber',
        ),
    ]
